### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by betatim** [wildtreetech/CRUMBS#3]
Where are we headed?

## Vision or very long term goal
A open-source platform that can be used for humanitarian GPS tracking and logging. hackable, low cost, and robust.

This roadmap is organized into stages of development, leading towards
a field tested design that can be extended for new needs.

## Stage 1
* [x] breadboard assembly of components
* [ ] record GPS traces in memory and SD card
  - [x] battery powered data logging (temperature not GPS)
  - [ ] battery powered GPS logging
* [x] simple REST end point to upload data to
* [ ] first iteration of a case to house components
* [ ] tools to overlay traces on existing maps
* [ ] define data format

## Stage 2
* [ ] record GPS traces for short time (~2min) and then sleep for a
      long time (10min)
* [ ] second iteration of case
* [ ] less simple REST end point to upload data to (identify individual devices, JSON API)
* [ ] combined power supply using 12V motorbike power and a battery

## Stage 3
* [ ] broadcast recorded GPS points when near a friendly WiFi AP
* [ ] server that receives GPS points, can display them and export to other
      formats

## Stage 4
* [ ] add GSM module to transmit location every N minutes
* [ ] server that listens for text messages and records them

**Comment by julianpistorius** [comment]
Have you thought about using [Low-Power Wide-Area Network (LPWAN)](https://en.wikipedia.org/wiki/LPWAN) like LoRa or Weightless? You could use this when there is no GSM coverage.
